### ISSUE TITLE
As tabelas não estão responsivas 

### ISSUE THREAD

**Issue by poliana-dev** [IFRN-SPP/cooplink#15]
colocar "table-responsive" na classe em todas as tabelas para facilitar o acesso rápido por celulares.
Parece que em algumas tabelas o dropdown buga.

**Comment by jleilhany** [comment]
- [x] Responsividade das tabelas: Todas as tabelas do sistema devem possuir a classe table-responsive, permitindo a visualização e navegação adequada em dispositivos móveis.
- [x] Funcionamento do dropdown: Os dropdowns presentes nas tabelas devem continuar funcionando corretamente após a aplicação da responsividade, sem cortes, sobreposição ou posicionamento incorreto.
- [x] Compatibilidade em diferentes telas: As tabelas devem manter sua estrutura e informações acessíveis em diferentes tamanhos de tela, especialmente em celulares, sem comprometer o funcionamento dos elementos de interação.                          
Tabelas no celular 
<img width="717" height="1600" alt="Image" src="https://github.com/user-attachments/assets/0d0cfa52-a833-4b55-9898-ea786ee9b852" />
<img width="717" height="1600" alt="Image" src="https://github.com/user-attachments/assets/b4c3031e-53e4-43ca-a12e-1898cc0e559b" />
