### ISSUE TITLE
criar tela de cadastro de pedido para administradores

### ISSUE THREAD

**Issue by anabsz** [IFRN-SPP/cooplink#2]
## Problema
Diferente dos usuários comuns, os administradores podem cadastrar pedidos para as instituições. Logo, um formulário diferente é necessário para cadastrar mais informações, como Instituição e Chamada.

## Tarefa
Criar uma tela estática de cadastro de pedido para administradores. Essa tela deve incluir um formulário com campos adicionais (Instituição e Chamada) em relação aos usuários comuns.

**Comment by elaynefernandes** [comment]
- [x] A tela deve apresentar um formulário de cadastro de pedido específico para administradores.
- [x] O formulário deve conter os campos adicionais de Instituição e Chamada.
- [x] A tela deve manter uma organização clara e adequada, permitindo visualizar e preencher todos os campos do cadastro.

<img width="1448" height="739" alt="Image" src="https://github.com/user-attachments/assets/d5719f07-6a8f-4da9-9ef3-90554f8407ec" />
