### ISSUE TITLE
fix settings.py para funcionar com esquema de deploy

### ISSUE THREAD

**Issue by dvcirilo** [IFRN-SPP/cooplink#23]
Algumas mudanças são necessárias:
- `STATIC_URL` perde a `/` inicial, senão dá bronca com o nginx (consequência de rodar o projeto em uma sub-location do servidor)
- `STATICFILES_DIRS` não precisa ficar num `if DEBUG`, em produção se não houver essa variável o `collectstatic` não consegue pegar tudo e jogar pra STATIC_ROOT.
- `STATIC_ROOT` vai pra uma variável de ambiente, pois no servidor ela vai ficar fora da pasta do projeto.

**Comment by jleilhany** [comment]
- [x] Carregamento dos arquivos estáticos: Após o deploy, o sistema deve carregar corretamente o CSS, imagens, ícones e demais elementos visuais em todas as páginas.
- [x] Funcionamento em produção: O sistema deve permanecer com a aparência e funcionalidades esperadas ao ser acessado pelo endereço de produção, sem erros relacionados a arquivos estáticos.
- [x] Acesso às páginas: Ao navegar entre as páginas do sistema, os recursos estáticos devem continuar carregando normalmente, sem páginas desconfiguradas ou elementos visuais ausentes.
