### ISSUE TITLE
adicionar links/botões para navegação

### ISSUE THREAD

**Issue by anabsz** [IFRN-SPP/cooplink#3]
## Problema
As telas estáticas não possuem uma forma de voltar para as páginas anteriores, há não ser pelos links da navbar. Algumas telas estão sem links importantes.
- Tabela de Instituição (Admin): sem link para detalhar
- Tabela de Pedidos (User): sem link para cadastrar.

## Tarefa
- Adicionar links/botões para voltar para as páginas anteriores
- Adicionar botões para cancelar formulários
- Adicionar links que estão faltando.

**Comment by elaynefernandes** [comment]
- [x] As telas devem possuir botões ou links para voltar às páginas anteriores, sem depender apenas da navbar.
- [x] Os formulários devem possuir um botão “Cancelar”, permitindo retornar sem concluir o cadastro.
- [x] A Tabela de Instituições (Admin) deve possuir link para detalhar e a Tabela de Pedidos (User) deve possuir link para cadastrar um novo pedido.

<img width="1634" height="723" alt="Image" src="https://github.com/user-attachments/assets/bb0e7f3c-c067-4a59-9095-9639915fbaf7" />

<img width="228" height="112" alt="Image" src="https://github.com/user-attachments/assets/66f9490f-b4d6-45f2-b8c5-5c72d401de1d" />

<img width="1366" height="573" alt="Image" src="https://github.com/user-attachments/assets/23d0347c-e613-4f63-84ad-448fa04cfaef" />

<img width="225" height="205" alt="Image" src="https://github.com/user-attachments/assets/98373a2f-d0e4-4a5b-95b1-b97891f25c84" />

<img width="1423" height="670" alt="Image" src="https://github.com/user-attachments/assets/d3be0d3c-5288-45b1-9f7e-e293d8985f31" />

<img width="214" height="142" alt="Image" src="https://github.com/user-attachments/assets/36a4491f-7154-4f43-8b75-65d707024d72" />
