### ISSUE TITLE
criar tela de detalhar pedido para administração 

### ISSUE THREAD

**Issue by anabsz** [IFRN-SPP/cooplink#5]
## Problema
De acordo com o levantamento de requisitos da equipe, a administração do sistema deve ter um tela para ver as informações do pedido, atualmente não feito.

## Tarefa 
Criar uma tela estática de detalhamento do pedido para administradores. Além das informações do pedido (Chamada, Autor, Instituição), deve haver uma tabela com Produto, Quantidade Pedida, Quantidade Disponível, Saldo Atual da Chamada e Situação. 

Elementos adicionais: 
- Botão para Voltar (para tabela de pedidos)
- Botão para Avaliar Pedido

**Comment by elaynefernandes** [comment]
- [x] A tela deve exibir as informações do pedido: Chamada, Autor e Instituição.
- [x]  A tabela deve apresentar Produto, Quantidade Pedida, Quantidade Disponível, Saldo Atual da Chamada e Situação.
- [x] A tela deve possuir os botões Voltar, para retornar à tabela de pedidos
- [x]  A tela deve possuir os botão para Avaliar Pedido.

<img width="329" height="153" alt="Image" src="https://github.com/user-attachments/assets/19998cbc-97d4-46b3-a1fa-f165f57567b3" />

<img width="1918" height="907" alt="Image" src="https://github.com/user-attachments/assets/bca436f8-17c7-4439-80f8-9b77675ed745" />

<img width="417" height="282" alt="Image" src="https://github.com/user-attachments/assets/ddfa095f-af8a-403b-ab02-f0f1f0ef8159" />
