### ISSUE TITLE
corrigir ``display: flex`` das telas de administração

### ISSUE THREAD

**Issue by anabsz** [IFRN-SPP/cooplink#6]
## Problema
Ao aumentar o tamanho do monitor, o ``container`` das telas de admin se esticam para se encaixar no tamanho do monitor.

## Tarefa
Corrigir o ``display`` do ``container`` para que as informações das telas não se estiquem em telas maiores, da mesma forma que é feito nas telas de usuário comum.

### Tela de Administração (50% de Zoom)
![image](https://github.com/IFRN-SPP/cooppotengi/assets/95952291/3126346c-217c-4ac8-aab5-1ea769e16ad9)

---

### Tela de Usuário Comum (50% de Zoom)
![image](https://github.com/IFRN-SPP/cooppotengi/assets/95952291/75252178-5f14-46a4-b587-db52580f1876)

**Comment by jleilhany** [comment]
- [x] Largura máxima do container: O container das telas de administração deve possuir uma largura máxima definida, impedindo que ele se estique indefinidamente em monitores maiores.
- [x] Responsividade: Em telas menores, o container deve continuar se adaptando ao tamanho disponível, sem causar cortes, sobreposição ou rolagem horizontal desnecessária.
- [x] Padronização com telas de usuário: O comportamento e o display do container das telas de administração devem seguir o mesmo padrão utilizado nas telas de usuário comum, mantendo as informações centralizadas e com tamanho adequado em diferentes resoluções.

<img width="1910" height="722" alt="Image" src="https://github.com/user-attachments/assets/d2d76080-6739-4426-8365-57710ad83622" />
