### ISSUE TITLE
Não é possível alterar a situação da chamada

### ISSUE THREAD

**Issue by dvcirilo** [IFRN-SPP/cooplink#7]
Depois de uma chamada criada, não é possível alterar sua situação.

**Comment by elaynefernandes** [comment]
- [x] Deve ser possível alterar a situação de uma chamada após sua criação
- [x] A nova situação deve ser salva corretamente no sistema.
- [x] A situação atualizada deve ser exibida corretamente na tabela de chamadas.

<img width="1299" height="142" alt="Image" src="https://github.com/user-attachments/assets/27a03328-001d-49c0-bca0-196b60e13427" />

<img width="273" height="232" alt="Image" src="https://github.com/user-attachments/assets/9eaa9342-6219-47e7-8c19-93497dab188b" />

<img width="1378" height="419" alt="Image" src="https://github.com/user-attachments/assets/f5954c1c-e6c9-4e5b-b8d6-95f95bc73b32" />

<img width="1351" height="386" alt="Image" src="https://github.com/user-attachments/assets/d2764337-a602-4af9-9f30-627153ef49e7" />
