### ISSUE TITLE
O usuário consegue tentar criar pedidos quando não há chamadas ativas

### ISSUE THREAD

**Issue by dvcirilo** [IFRN-SPP/cooplink#8]
Quando há apenas uma chamada inativa, a opção de criar pedido aparece para o usuário, que pode selecionar a chamada inativa e o cadastro falha com uma exception que não foi tratada.

**Comment by elaynefernandes** [comment]
- [x] A opção de criar pedido não deve aparecer quando não houver chamadas ativas.

- [x] O usuário não deve conseguir selecionar ou criar pedidos para chamadas inativas.

- [x] O sistema deve exibir uma mensagem informativa ao usuário quando não houver chamadas ativas disponíveis.

<img width="1465" height="743" alt="Image" src="https://github.com/user-attachments/assets/b6f4b1f4-db03-4a8b-9945-7507f05fbf40" />
