### ISSUE TITLE
Ocultar ações que o usuário não tem permissão

### ISSUE THREAD

**Issue by dvcirilo** [IFRN-SPP/cooplink#9]
As opções de  "Editar chamada" e "Editar produtos" aparecem para usuários sem permissão em detalhar chamadas.

Apesar de ser tratado com um alert de que o usuário não tem permissão, seria mais simples pro usuário nem ver esses botões.

**Comment by elaynefernandes** [comment]
- [x] Usuários sem permissão não veem os botões — sem alertas, sem mensagens de erro.

ADMIN:
<img width="1197" height="550" alt="Image" src="https://github.com/user-attachments/assets/ae3dee0c-527b-40af-a3b8-b0ccf46b6da8" />

USUÁRIO:

<img width="1252" height="435" alt="Image" src="https://github.com/user-attachments/assets/ccdb8e71-f560-4529-9300-ad9992ceae4e" />
